# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ukd-micro-uat
  region: ap-south-1

nodeGroups:
  - name: workerNodeGroupe-uat
    instanceType: r5.xlarge
    desiredCapacity: 2
    nodes-min: 2 
    nodes-max: 3
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: ukd-mirco-uat

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager", "scheduler", "authenticator"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
