apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kaniko-cache-warmer
  namespace: jenkins
spec:
  concurrencyPolicy: "Forbid"
  schedule: "45 18 * * *"
  jobTemplate:
    spec:
      template:
        spec: 
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists             
          containers:
          - name: kaniko-cache-warmer
            image: gcr.io/kaniko-project/warmer:latest
            args: ["--cache-dir=/cache",
                  "--image=nithindv/alpine-maven-jdk-8:gcp",
                  "--image=egovio/citizen:latest",
                  "--image=egovio/pt-calculator-v2:latest",
                  "--image=egovio/nginx:latest",
                  "--image=egovio/firenoc-services:latest",
                  "--image=egovio/8-openjdk-alpine",
                  "--image=egovio/alpine-maven-builder-jdk-8:gcp",         
                  "--image=egovio/flyway:4.1.2",         
                  "--image=egovio/alpine-node-builder-10:yarn"         
                  ]               
            volumeMounts:
              - name: kaniko-cache
                mountPath: /cache
          volumes:
            - name: kaniko-cache
              persistentVolumeClaim:
                claimName: kaniko-cache-claim
          restartPolicy: Never                     