apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: egov-frontend
        tier: frontend
    spec:
      containers:
        - name: egov-frontend
          image: egovio/frontend:1.0.0
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          env:
          - name: REDIS_HOST
            value: redis-master
          - name: DB_HOST
            value: "ap1-qa-psql-monolith.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com"
          - name: DB_USER
            value: egov
          - name: DB_NAME
            value: egov_qa
          - name: DB_PASSWORD
            value: "I<3ChanaMasala!"
          - name: REST_HOST
            value: egov-pgrrest
          - name: REST_PORT
            value: "9090"
          - name: MASTER_SERVER
            value: "true"
          - name: CORS_ENABLED
            value: "true"
          ports:
          - containerPort: 8080

