apiVersion: v1
kind: Service
metadata:
  name: egov-frontend
  labels:
    app: egov-frontend
    tier: frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-frontend
    tier: frontend
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.5.0/24
  - 10.0.51.0/24
