apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-notification
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: egov-notification
        tier: frontend
    spec:
      containers:
        - name: egov-notification
          image: egovio/notification:latest
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          env:
          - name: ADVERTISED_HOST
            value: kafka
          - name: ADVERTISED_PORT
            value: "9092"
          ports:
          - containerPort: 8080

