apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    tier: backend
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
