apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        tier: backend
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 9092
