apiVersion: v1
kind: Service
metadata:
  name: egov-searcher
  namespace: egov
  labels:
    app: egov-searcher
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-searcher
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-searcher
  namespace: egov
spec:
  replicas: {{conf['egov-searcher']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-searcher
        group: core
    spec:
      volumes:
      - name: git-secret
        secret:
          secretName: git-creds
          defaultMode: 288 # = mode 0440   
      - name: workdir
        emptyDir: {}       
      initContainers: 
      - name: "git-sync"
        image: "{{conf["git-sync"]["image"]}}"
        env: 
        - name: "GIT_SYNC_REPO"
          value: "{{conf['egov-searcher']['repo']}}"
        - name: "GIT_SYNC_BRANCH"
          value: "{{conf['egov-searcher']['branch']}}"        
        - name: "GIT_SYNC_DEPTH"
          value: "1"            
        - name: "GIT_SYNC_ONE_TIME"
          value: "true"          
        - name: "GIT_SYNC_SSH"
          value: "true"      
        - name: "GIT_SYNC_ROOT"
          value: "/work-dir"      
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret              
        - name: workdir
          mountPath: "/work-dir"         
        imagePullPolicy: "IfNotPresent"
      securityContext:
        fsGroup: 65533 # to make SSH key readable 
      containers:
      - name: egov-searcher
        image: {{conf['egov-searcher']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SEARCH_YAML_PATH
          value: "{{conf['egov-searcher']['search-yaml-path']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SERVER_TOMCAT_MAX_THREADS
          value: "{{conf['egov-config']['server-tomcat-max-threads']}}"  
        - name: SERVER_TOMCAT_MAX_CONNECTIONS
          value: "{{conf['egov-config']['server-tomcat-max-connections']}}" 
        - name: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
          value: "{{conf['egov-config']['spring-datasource-tomcat-max-active']}}"              
        - name: JAVA_OPTS
          value: "{{conf['egov-searcher']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: JAEGER_SERVICE_NAME
          value: egov-searcher
        - name: JAEGER_SAMPLER_TYPE
          value: remote
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
          value: "$(JAEGER_AGENT_HOST):5778"              
        - name: SECURITY_BASIC_ENABLED
          value: "false"  
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false" 
{% if conf['egov-searcher']['tracing-enabled']%}          
        - name: TRACER_OPENTRACING_ENABLED
          value: "true" 
{% endif %}
        volumeMounts:              
        - name: workdir
          mountPath: "/work-dir"             
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{conf['egov-searcher']['memory_limits'] or "512Mi"}}"
