# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ukd-micro-prod
  region: ap-south-1

vpc:
  id: "vpc-0c39f512cdd645abf"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      ap-south-1a:
        id: "subnet-01e3d5aff1cf382fb"
nodeGroups:
  - name: workerNodeGroupe-prod
    instanceType: r5.xlarge
    desiredCapacity: 4
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: ukd-mirco-prod

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager", "scheduler", "authenticator"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
