apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}
  namespace: egov
  labels:
    app: {{ service_name }}
    group: {{ project }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: {{ service_name }}
    group: {{ project }}
---
