apiVersion: v1
kind: Service
metadata:
  name: citizen
  namespace: egov
  labels:
    app: citizen
    group: web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: citizen
    group: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: citizen
  namespace: egov
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{conf['citizen']['replicas']}}
  template:
    metadata:
      labels:
        app: citizen
        group: web
    spec:  
{% if conf['citizen']['custom-js-injection'] %} 
      volumes:         
      - name: js-injection
        configMap:
          name: citizen-js-injection
{% endif %}       
      containers:     
      - name: citizen
        image: {{conf['citizen']['images'][0]}}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /citizen/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        volumeMounts:
{% if conf['citizen']['custom-js-injection'] %}               
        - mountPath: /etc/nginx/conf.d/sub_filter.conf
          name: js-injection    
          subPath: sub_filter.conf
{% endif %}           
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "{{ conf['citizen']['memory_limits'] or "128Mi"}}"
