apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: egov-telemetry-batch-process
  namespace: egov
spec:
  concurrencyPolicy: "Forbid"
  schedule: "{{conf['egov-telemetry-batch-process']['schedule']}}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: egov-telemetry-batch-process
            image: "{{ conf['egov-telemetry-batch-process']['images'][0] }}"
            env:
            - name: ES_HOST
              value: "{{ conf['logging-config']['es-host'] }}"
            - name: ES_PORT
              value: "9200"             
            - name: ES_NODE_WAN_ONLY
              value: "true"
            - name: KAFKA_OUTPUT_TOPIC
              value: "batch-telemetry"
            - name: SESSION_TIMEOUT
              value: "30"
            - name: JAVA_OPTS
              value: '-Xmx512m -Xms512m'
            - name: KAFKA_BOOTSTRAP_SERVER_CONFIG
              value: "{{ conf['kafka-config']['kafka-infra-brokers'] }}"
            - name: ES_OUTPUT_TELEMETRY_BATCH_INDEX
              value: "batchtelemetryindex-v1*/general/"
            - name: ES_INPUT_TELEMETRY_INDEX
              value: "telemetryindex-v1*/general/"
            - name: DATE
              value: ""
            resources:
              requests:
                memory: "512Mi"
              limits:
                memory: "1024Mi"
          restartPolicy: Never
